### ISSUE TITLE
Touch USB Connection Issue

### ISSUE THREAD

**Issue by bsunal** [bharatm11/Geomagic_Touch_ROS_Drivers#2]
Dear @bharatm11 

I have installed all the drivers and your repository in three different computers with all the USB ports however I have not managed to get the haptic devices connected in Ubuntu 16.04 with any of them. First of all 3D Systems suggest that the vendor ID and device ID must be 0301:2988, but ID's of my device are 2988:0302.
![Screenshot from 2020-07-07 13-03-56](https://user-images.githubusercontent.com/22602060/86772099-0f091880-c05c-11ea-8c0b-5d84af0677fc.png)
When I first open the Geomagic Touch Setup, a serial number is shown on the screen, however when I click on "Apply" serial number disappears and it says "No devices found instead. Geomagic Touch Diagnostic cannot initialize the the device at all.
![Screenshot from 2020-07-07 13-04-39](https://user-images.githubusercontent.com/22602060/86772355-8048cb80-c05c-11ea-9a38-ad17eee9768c.png)
![Screenshot from 2020-07-07 13-06-06](https://user-images.githubusercontent.com/22602060/86772360-83dc5280-c05c-11ea-8504-6279769aedce.png)
Testing any of the OpenHaptics example codes causes the following error.
![Screenshot from 2020-07-07 13-07-33](https://user-images.githubusercontent.com/22602060/86772409-a4a4a800-c05c-11ea-9997-12192eb82ba9.png)
Finally, running "roslaunch omni_common omni_state.launch" causes the following error.
![Screenshot from 2020-07-07 13-10-12](https://user-images.githubusercontent.com/22602060/86772473-cbfb7500-c05c-11ea-82a3-46bcec8bb216.png)
I have two devices, and I have separately tested them in all the USB ports of 3 different computers (2 laptops and 1 desktop). On Windows everything works fine on the same computers but in Ubuntu 16.04 I get the same errors for both devices in all of the computers. I have checked similar errors in 3D systems forums but none of the solutions worked. Do you know any solution for this problem?

**Comment by bharatm11** [comment]
@bsunal apologies for the late response. Were you able to fix this? I feel as long as the Diagnostic setup shows some serial number you should be alright. I have never tested an of the OpenHaptics example codes. I suggest trying the roslaunch on a fresh setup.

**Comment by bsunal** [comment]
@bharatm11 Yes, I fixed the problem. I ended up e-mailing OpenHaptics about the issue. They have said that they are in process of updating their webpage and the drivers are outdated. They have sent me a new link (https://support.3dsystems.com/s/article/OpenHaptics-for-Linux-Developer-Edition-v34?language=en_US in case anyone else is having the same problem) I updated my system to Ubuntu 18.04 with the drivers from the link and ROS Melodic. Everything works fine now.

**Comment by bharatm11** [comment]
@bsunal thanks for letting me know. I will update the link on the readme.

**Comment by qwewr** [comment]
Dear@bsunal,I have encountered the same problem, but it is still the same after downloading the new version of the software. How did you solve it at that time.think you

**Comment by bharatm11** [comment]
3D Systems customer support suggested using a powered USB-hub which resolved connectivity issues for some users.
